<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<!-- Dejamos a Swashbuckle solo para que no tenga conflictos -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LegalDocsPro.Application\LegalDocsPro.Application.csproj" />
		<ProjectReference Include="..\LegalDocsPro.Infrastructure\LegalDocsPro.Infrastructure.csproj" />
	</ItemGroup>

</Project>
